# פרומפטים לטיפול בשגיאות

errors:
  general: |
    מצטער, התרחשה שגיאה כללית. אנא נסה שוב מאוחר יותר.
    אם הבעיה נמשכת, צור קשר עם התמיכה.

  api_error: |
    מצטער, התרחשה שגיאה בתקשורת עם השרת.
    קוד שגיאה: {error_code}
    פרטי שגיאה: {error_details}
    אנא נסה שוב מאוחר יותר.

  validation_error: |
    הנתונים שהוזנו אינם תקינים:
    {validation_errors}
    אנא תקן את השגיאות ונסה שוב.

  permission_error: |
    אין לך הרשאות מתאימות לבצע פעולה זו.
    אנא צור קשר עם מנהל המערכת לקבלת הרשאות.

  not_found_error: |
    הפריט המבוקש לא נמצא.
    אנא ודא שהפרטים נכונים ונסה שוב.

  timeout_error: |
    הפעולה ארכה זמן רב מדי.
    אנא נסה שוב או פצל את הבקשה לחלקים קטנים יותר.

  quota_error: |
    חרגת ממכסת השימוש היומית.
    אנא נסה שוב מחר או שדרג את החבילה שלך.

  connection_error: |
    לא ניתן להתחבר לשרת.
    אנא בדוק את חיבור האינטרנט שלך ונסה שוב.

templates:
  error_message: |
    שגיאה: {error_type}
    הודעה: {error_message}
    {error_details}

  error_with_suggestion: |
    שגיאה: {error_type}
    הודעה: {error_message}
    הצעה לפתרון: {suggestion} 